feat: workflow change for 2.4.0

diff --git a/.github/workflows/workflow.yaml b/.github/workflows/workflow.yaml
--- a/.github/workflows/workflow.yaml
+++ b/.github/workflows/workflow.yaml
@@ -3,7 +3,7 @@ name: VSS Deploy
 on:
   push:
     branches:
-      - develop
+      - develop-2.4.0
     paths-ignore:
       - 'deploy/k8s/vlm/Qwen/model-config.yaml'
       - 'deploy/k8s/vlm/VILA/model-config.yaml'
@@ -67,7 +67,6 @@ jobs:
         with:
           ssh-private-key: |
             ${{ secrets.SSH_PRIVATE_KEY }}
-
       - name: Login to NGC
         uses: docker/login-action@v3
         with:
@@ -109,33 +108,47 @@ jobs:
           IMAGE_TAG="${{ inputs.image_tag || github.sha }}"
           find deploy/k8s/${{ env.PROJECT_ENV }} -type f -name "*.yaml" -exec sed -i "s/IMAGE_TAG/$IMAGE_TAG/g" {} +
           kubectl apply -f deploy/k8s/${{ env.PROJECT_ENV }} --recursive
+      # - name: Wait for image pull job to complete (up to 20min)
+      #   run: |
+      #     for i in {1..80}; do
+      #       STATUS=$(kubectl get job image-prepull -n vss -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}')
+      #       FAILED=$(kubectl get job image-prepull -n vss -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}')
+      #       if [ "$STATUS" == "True" ]; then
+      #         echo "Job completed successfully."
+      #         exit 0
+      #       elif [ "$FAILED" == "True" ]; then
+      #         echo "Job failed!"
+      #         kubectl describe job image-prepull -n vss
+      #         exit 1
+      #       fi
+      #       echo "Waiting for job to complete..."
+      #       sleep 15
+      #     done
+      #     echo "Timeout reached. Job did not complete in time."
+      #     exit 1
 
-      - name: Wait for image pull job to complete (up to 20min)
-        run: |
-          for i in {1..40}; do
-            STATUS=$(kubectl get job image-prepull -n vss -o jsonpath='{.status.conditions[?(@.type=="Complete")].status}')
-            FAILED=$(kubectl get job image-prepull -n vss -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}')
-            if [ "$STATUS" == "True" ]; then
-              echo "Job completed successfully."
-              exit 0
-            elif [ "$FAILED" == "True" ]; then
-              echo "Job failed!"
-              kubectl describe job image-prepull -n vss
-              exit 1
-            fi
-            echo "Waiting for job to complete..."
-            sleep 60
-          done
-          echo "Timeout reached. Job did not complete in time."
-          exit 1
-
-      - name: Clean up prepull job
-        run: kubectl delete job image-prepull -n vss --ignore-not-found
+      # - name: Clean up prepull job
+      #   run: kubectl delete job image-prepull -n vss --ignore-not-found
 
       - name: Deploy vss app to Onprem
         run: |
           IMAGE_TAG="${{ inputs.image_tag || github.sha }}"
-          kubectl scale deployment vss-vss-deployment -n vss --replicas=0
+          kubectl scale deployment vss-vss-deployment -n vss-240 --replicas=0
           find deploy/helm/values/${{ env.PROJECT_ENV }}.yaml -exec sed -i "s/IMAGE_TAG/$IMAGE_TAG/g" {} +
-          helm upgrade vss deploy/helm/nvidia-blueprint-vss-2.4.0.tgz -f deploy/helm/values/${{ env.PROJECT_ENV }}.yaml -n vss --install
-          kubectl scale deployment vss-vss-deployment -n vss --replicas=1
+          helm upgrade vss deploy/helm/nvidia-blueprint-vss-2.4.0.tgz -f deploy/helm/values/${{ env.PROJECT_ENV }}.yaml -n vss-240 --install
+          kubectl scale deployment vss-vss-deployment -n vss-240 --replicas=1
+
+      - name: Patch schedulerName for deployments
+        run: |
+          kubectl patch deployment nemo-embedding-embedding-deployment -n vss-240 -p '{"spec":{"template":{"spec":{"schedulerName":"bin-packing-scheduler"}}}}'
+          kubectl patch deployment nemo-rerank-ranking-deployment -n vss-240 -p '{"spec":{"template":{"spec":{"schedulerName":"bin-packing-scheduler"}}}}'
+          kubectl patch deployment vss-vss-deployment -n vss-240 -p '{"spec":{"template":{"spec":{"schedulerName":"bin-packing-scheduler"}}}}'
+
+      - name: scale down not use service
+        run: |
+          # llm server scale down (not use)
+          kubectl scale statefulset vss -n vss-240 --replicas=0
+          # embedding and reranker scale down
+          kubectl scale deployment vss-vss-deployment -n vss-240 --replicas=0
+          kubectl scale deployment nemo-embedding-embedding-deployment -n vss-240 --replicas=0
+          kubectl scale deployment nemo-rerank-ranking-deployment -n vss-240 --replicas=0
